version: '3'

services:
  app:
    container_name: app
    image: jesus18reyes/pruebas-server:0.0.14
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: ${DATABASE_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile


  db:
    container_name: postgres-db
    image: postgres:15.1
    volumes:
      - pg-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: pruebasDB
    ports:
      - 5432:5432
    restart: always
  
  adminer: 
    image: adminer
    depends_on:
      - db
    restart: always
    ports:
      - 80:8080
    

volumes:
  pg-db:
    external:
      false